// configuration variables for the front-end app that are common to all environemnts
module.exports = {
  storeName: "ClipCast",
  storeUrl: "https://www.clipcast.it",
  imageBase: "https://www.clipcast.it",
  storeAddress1: "",
  storeCity: "",
  storeState: "",
  storeZip: "",
  storePhone: "",
  storePhoneMobile: "",
  siteCode: "clipcast",
  masterBrand: "",
  captureModalDelay: 5000,
  alertTimeout: 3500,
  sessionTimeout: 1800,
  missingImage: "/assets/images/default_image.png",
  debounceDefault: 40,
  userInterfaceConfig: {
    id: "#app",
    bootstrap: {
      tooltip: {
        attr: 'data-bs-toggle="tooltip"',
      },
      popover: {
        attr: 'data-bs-toggle="popover"',
      },
      modal: {
        attr: 'data-bs-toggle="modal"',
        dismissAttr: 'data-bs-dismiss="modal"',
        event: {
          hidden: "hidden.bs.modal",
        },
      },
      nav: {
        class: "nav",
        tabs: {
          class: "nav-tabs",
          activeClass: "active",
          itemClass: "nav-item",
          itemLinkClass: "nav-link",
        },
      },
    },
    header: {
      id: "#header",
      class: "app-header",
      hasScrollClass: "has-scroll",
    },
    sidebar: {
      id: "#sidebar",
      class: "app-sidebar",
      scrollBar: {
        localStorage: "appSidebarScrollPosition",
        dom: "",
      },
      menu: {
        class: "menu",
        initAttr: "data-init",
        animationTime: 0,
        itemClass: "menu-item",
        itemLinkClass: "menu-link",
        hasSubClass: "has-sub",
        activeClass: "active",
        expandingClass: "expanding",
        expandClass: "expand",
        submenu: {
          class: "menu-submenu",
        },
      },
      mobile: {
        toggleAttr: 'data-toggle="app-sidebar-mobile"',
        dismissAttr: 'data-dismiss="app-sidebar-mobile"',
        toggledClass: "app-sidebar-mobile-toggled",
        closedClass: "app-sidebar-mobile-closed",
        backdrop: {
          class: "app-sidebar-mobile-backdrop",
        },
      },
      minify: {
        toggleAttr: 'data-toggle="app-sidebar-minify"',
        toggledClass: "app-sidebar-minified",
        cookieName: "app-sidebar-minified",
      },
      floatSubmenu: {
        id: "#app-sidebar-float-submenu",
        dom: "",
        timeout: "",
        class: "app-sidebar-float-submenu",
        container: {
          class: "app-sidebar-float-submenu-container",
        },
        arrow: {
          id: "#app-sidebar-float-submenu-arrow",
          class: "app-sidebar-float-submenu-arrow",
        },
        line: {
          id: "#app-sidebar-float-submenu-line",
          class: "app-sidebar-float-submenu-line",
        },
        overflow: {
          class: "overflow-scroll mh-100vh",
        },
      },
      search: {
        class: "menu-search",
        toggleAttr: 'data-sidebar-search="true"',
        hideClass: "d-none",
        foundClass: "has-text",
      },
      transparent: {
        class: "app-sidebar-transparent",
      },
    },
    topNav: {
      id: "#top-nav",
      class: "app-top-nav",
      mobile: {
        toggleAttr: 'data-toggle="app-top-nav-mobile"',
      },
      menu: {
        class: "menu",
        itemClass: "menu-item",
        itemLinkClass: "menu-link",
        activeClass: "active",
        hasSubClass: "has-sub",
        expandClass: "expand",
        submenu: {
          class: "menu-submenu",
        },
      },
      control: {
        class: "menu-control",
        startClass: "menu-control-start",
        endClass: "menu-control-end",
        showClass: "show",
        buttonPrev: {
          class: "menu-control-start",
          toggleAttr: 'data-toggle="app-top-menu-prev"',
        },
        buttonNext: {
          class: "menu-control-end",
          toggleAttr: 'data-toggle="app-top-menu-next"',
        },
      },
    },
    scrollBar: {
      attr: 'data-scrollbar="true"',
      skipMobileAttr: "data-skip-mobile",
      heightAttr: "data-height",
      wheelPropagationAttr: "data-wheel-propagation",
    },
    content: {
      id: "#content",
      class: "app-content",
      fullHeight: {
        class: "app-content-full-height",
      },
      fullWidth: {
        class: "app-content-full-width",
      },
    },
    layout: {
      sidebarLight: {
        class: "app-with-light-sidebar",
      },
      sidebarEnd: {
        class: "app-with-end-sidebar",
      },
      sidebarWide: {
        class: "app-with-wide-sidebar",
      },
      sidebarMinified: {
        class: "app-sidebar-minified",
      },
      sidebarTwo: {
        class: "app-with-two-sidebar",
      },
      withoutHeader: {
        class: "app-without-header",
      },
      withoutSidebar: {
        class: "app-without-sidebar",
      },
      topMenu: {
        class: "app-with-top-menu",
      },
      boxedLayout: {
        class: "boxed-layout",
      },
    },
    scrollToTopBtn: {
      showClass: "show",
      heightShow: 200,
      toggleAttr: 'data-toggle="scroll-to-top"',
      scrollSpeed: 500,
    },
    scrollTo: {
      attr: 'data-toggle="scroll-to"',
      target: "data-target",
      linkTarget: "href",
    },
    dismissClass: {
      toggleAttr: "data-dismiss-class",
      targetAttr: "data-dismiss-target",
    },
    toggleClass: {
      toggleAttr: "data-toggle-class",
      targetAttr: "data-toggle-target",
    },
    variablePrefix: "bs-",
    variableFontList: [
      "body-font-family",
      "body-font-size",
      "body-font-weight",
      "body-line-height",
    ],
    variableColorList: [
      "theme",
      "theme-rgb",
      "theme-color",
      "theme-color-rgb",
      "default",
      "default-rgb",
      "primary",
      "primary-rgb",
      "primary-bg-subtle",
      "primary-text",
      "primary-border-subtle",
      "secondary",
      "secondary-rgb",
      "secondary-bg-subtle",
      "secondary-text",
      "secondary-border-subtle",
      "success",
      "success-rgb",
      "success-bg-subtle",
      "success-text",
      "success-border-subtle",
      "warning",
      "warning-rgb",
      "warning-bg-subtle",
      "warning-text",
      "warning-border-subtle",
      "info",
      "info-rgb",
      "info-bg-subtle",
      "info-text",
      "info-border-subtle",
      "danger",
      "danger-rgb",
      "danger-bg-subtle",
      "danger-text",
      "danger-border-subtle",
      "light",
      "light-rgb",
      "light-bg-subtle",
      "light-text",
      "light-border-subtle",
      "dark",
      "dark-rgb",
      "dark-bg-subtle",
      "dark-text",
      "dark-border-subtle",
      "inverse",
      "inverse-rgb",
      "white",
      "white-rgb",
      "black",
      "black-rgb",
      "teal",
      "teal-rgb",
      "indigo",
      "indigo-rgb",
      "purple",
      "purple-rgb",
      "yellow",
      "yellow-rgb",
      "pink",
      "pink-rgb",
      "cyan",
      "cyan-rgb",
      "gray-100",
      "gray-200",
      "gray-300",
      "gray-400",
      "gray-500",
      "gray-600",
      "gray-700",
      "gray-800",
      "gray-900",
      "gray-100-rgb",
      "gray-200-rgb",
      "gray-300-rgb",
      "gray-400-rgb",
      "gray-500-rgb",
      "gray-600-rgb",
      "gray-700-rgb",
      "gray-800-rgb",
      "gray-900-rgb",
      "muted",
      "muted-rgb",
      "emphasis-color",
      "emphasis-color-rgb",
      "body-bg",
      "body-bg-rgb",
      "body-color",
      "body-color-rgb",
      "heading-color",
      "secondary-color",
      "secondary-color-rgb",
      "secondary-bg",
      "secondary-bg-rgb",
      "tertiary-color",
      "tertiary-color-rgb",
      "tertiary-bg",
      "tertiary-bg-rgb",
      "link-color",
      "link-color-rgb",
      "link-hover-color",
      "link-hover-color-rgb",
      "border-color",
      "border-color-translucent",
    ],
    font: {},
    color: {},
    card: {
      expand: {
        status: false,
        toggleAttr: 'data-toggle="card-expand"',
        toggleTitle: "Expand / Compress",
        class: "card-expand",
      },
    },
    init: {
      attr: "data-init",
      class: "app-init",
    },
    animation: {
      attr: "data-animation",
      valueAttr: "data-value",
      speed: 300,
      effect: "swing",
    },
    breakpoints: {
      xs: 0,
      sm: 576,
      md: 768,
      lg: 992,
      xl: 1200,
      xxl: 1660,
      xxxl: 1900,
    },
  },
};
