FROM python:3.12

# Set environment variables
ENV PIP_NO_CACHE_DIR=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

# install base packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    mariadb-client \
    less \
    vim \
    locate \
    iputils-ping \
    ssh \
    rsync \
    ffmpeg \
    cron \
    redis-tools \
    task-spooler \
    direnv \
    curl \
    ca-certificates \
    fonts-liberation \
    libnss3 \
    libx11-xcb1 \
    libxcomposite1 \
    libxrandr2 \
    libxdamage1 \
    libxshmfence1 \
    libxtst6 \
    libasound2 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libdbus-1-3 \
    libdrm2 \
    libgbm1 \
    libgtk-3-0 \
    libpango-1.0-0 \
    libx11-6 \
    libxext6 \
    xauth \
    xvfb \
    lsb-release \
    wget && \
    rm -rf /var/lib/apt/lists/*
RUN pip install --upgrade pip
RUN mkdir /project
WORKDIR /project
COPY manage.py /project/manage.py
COPY requirements.txt /project/requirements.txt
RUN pip3 install -r /project/requirements.txt
RUN pip install playwright && playwright install
# Set up a script to run Playwright with Xvfb
RUN echo "#!/bin/bash\nxvfb-run -a \"\$@\"" > /usr/bin/playwright-with-xvfb && chmod +x /usr/bin/playwright-with-xvfb

COPY clipcast_crontab /etc/cron.d/clipcast_crontab
COPY .envrc /project/.envrc
RUN chmod 0644 /etc/cron.d/clipcast_crontab
RUN crontab /etc/cron.d/clipcast_crontab

COPY bin/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]